// <auto-generated />
using System;
using ContaBancaria.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContaBancaria.Data.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20220619012350_ContaBancaria.1")]
    partial class ContaBancaria1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.Banco", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUID");

                    b.Property<int>("Agencia")
                        .HasColumnName("AGENCIA")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnName("NUMERO")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("BANCO");
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.Conta", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUID");

                    b.Property<Guid>("GuidBanco")
                        .HasColumnName("GUID_BANCO");

                    b.Property<long>("Numero")
                        .HasColumnName("NUMERO")
                        .HasColumnType("bigint");

                    b.HasKey("Guid");

                    b.HasIndex("GuidBanco");

                    b.ToTable("CONTA");
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.ExtratoConta", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUID");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnName("DATA_OPERACAO")
                        .HasColumnType("datetime");

                    b.Property<Guid>("GuidConta")
                        .HasColumnName("GUID_CONTA");

                    b.Property<Guid>("GuidContaOrigem")
                        .HasColumnName("GUID_CONTA_ORIGEM");

                    b.Property<byte>("TipoOperacao")
                        .HasColumnName("TIPO_OPERACAO");

                    b.Property<byte?>("TipoTaxaBancaria")
                        .HasColumnName("TIPO_TAXA_BANCARIA");

                    b.Property<decimal>("Valor")
                        .HasColumnName("VALOR")
                        .HasColumnType("money");

                    b.HasKey("Guid");

                    b.HasIndex("GuidConta");

                    b.ToTable("EXTRATO_CONTA");
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.TaxaBancaria", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GUID");

                    b.Property<string>("Descricao")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("GuidBanco")
                        .HasColumnName("GUID_BANCO");

                    b.Property<byte?>("Tipo")
                        .HasColumnName("TIPO");

                    b.Property<byte>("TipoValor")
                        .HasColumnName("TIPO_VALOR");

                    b.Property<decimal>("Valor")
                        .HasColumnName("VALOR")
                        .HasColumnType("numeric");

                    b.HasKey("Guid");

                    b.HasIndex("GuidBanco");

                    b.ToTable("TAXA_BANCARIA");
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.Conta", b =>
                {
                    b.HasOne("ContaBancaria.Dominio.Entidades.Banco", "Banco")
                        .WithMany("Contas")
                        .HasForeignKey("GuidBanco")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.ExtratoConta", b =>
                {
                    b.HasOne("ContaBancaria.Dominio.Entidades.Conta", "Conta")
                        .WithMany("Extrato")
                        .HasForeignKey("GuidConta")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContaBancaria.Dominio.Entidades.TaxaBancaria", b =>
                {
                    b.HasOne("ContaBancaria.Dominio.Entidades.Banco", "Banco")
                        .WithMany("TaxasBancarias")
                        .HasForeignKey("GuidBanco")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
